sudo: 'required'

services:
  - 'docker'

language:
  - 'bash'

env:
  global:
    - NODE_RED_VERSION=0.18.4
    - IMAGE=raymondmm/node-red
    - QEMU_VERSION=v2.11.1

before_install:
  - ./.docker/docker.sh prepare

script:
  - ./update.sh $NODE_RED_VERSION
  - ./.docker/docker.sh build

after_success:
  - >
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      # Docker Hub Login
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Tag all images
      ./.docker/docker.sh tag

      # Push all images
      ./.docker/docker.sh push

      # Create and push manifest list
      ./.docker/docker.sh manifest-list

      # Docker Hub Logout
      docker logout
    fi

# don't notify me when things fail
notifications:
    email: false
