sudo: required

dist: xenial

services: docker

language: bash

env:
  global:
    - NODE_RED_VERSION=x.y.z
    - TARGET=raymondmm/node-red
    - QEMU_VERSION=v4.0.0
  matrix:
    # No Python Images
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=x86_64  ARCH=amd64 PYTHON_VERSION=0
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=arm     ARCH=arm32v6 PYTHON_VERSION=0
    ##- DOCKER_FILE=Dockerfile.alpine BUILD_FROM=arm32v7/node:10-alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=arm     ARCH=arm32v7 PYTHON_VERSION=0
    #- DOCKER_FILE=Dockerfile.slim   NODE_VERSION=10 OS=slim   QEMU_ARCH=arm     ARCH=arm32v7 PYTHON_VERSION=0
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=aarch64 ARCH=arm64v8 PYTHON_VERSION=0

    # Python 2 Images
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=x86_64  ARCH=amd64 PYTHON_VERSION=2
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=arm     ARCH=arm32v6 PYTHON_VERSION=2
    ##- DOCKER_FILE=Dockerfile.alpine BUILD_FROM=arm32v7/node:10-alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=arm     ARCH=arm32v7 PYTHON_VERSION=0
    #- DOCKER_FILE=Dockerfile.slim   NODE_VERSION=10 OS=slim   QEMU_ARCH=arm     ARCH=arm32v7 PYTHON_VERSION=2
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=aarch64 ARCH=arm64v8 PYTHON_VERSION=2

    # Python 3 Images
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=x86_64  ARCH=amd64 PYTHON_VERSION=3
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=arm     ARCH=arm32v6 PYTHON_VERSION=3
    ##- DOCKER_FILE=Dockerfile.alpine BUILD_FROM=arm32v7/node:10-alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=arm     ARCH=arm32v7 PYTHON_VERSION=0
    #- DOCKER_FILE=Dockerfile.slim   NODE_VERSION=10 OS=slim   QEMU_ARCH=arm     ARCH=arm32v7 PYTHON_VERSION=3
    - DOCKER_FILE=Dockerfile.alpine NODE_VERSION=10 OS=alpine QEMU_ARCH=aarch64 ARCH=arm64v8 PYTHON_VERSION=3

before_install:
  - ./docker.sh prepare

install: true

before_script:
    # Set BUILD_VERSION
    - if [ ! -z "${TRAVIS_TAG}" ]; then export BUILD_VERSION=${TRAVIS_TAG:1}; else export BUILD_VERSION=beta; fi

script:
  # Update NODE_RED_VERSION from package.json
  - ./update_version.sh

  # Build Docker image
  - ./docker.sh build

  # Test Docker image
  - ./docker.sh test

  # Push Docker image
  - >
    if [ ! -z "${TRAVIS_TAG}" ]; then
      # Tag Docker image
      ./docker.sh tag

      # Docker Login
      echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Push Docker image
      ./docker.sh push

      # Docker Logout
      docker logout
    fi

jobs:
    include:
        - stage: manifest
          if: tag =~ ^v
          script:
              # Update NODE_RED_VERSION from package.json
              - ./update_version.sh

              # Create and push Docker manifest lists (TODO move to function)
              # Docker Login
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

              # Create and Push Docker Manifest Lists to Docker Hub
              - echo "Create manifest list for all docker images."
              - ./docker.sh manifest-list

              # Docker Logout
              - docker logout

# notify me when things fail
notifications:
    email: true
