# make use of vm's
sudo: 'required'

# have the docker service set up (we'll update it later)
services:
  - 'docker'

language:
  - 'bash'

env:
  - QEMU_VERSION=v2.11.1

before_install:
  # prepare the machine before any code installation scripts
  - './.travis/main.sh'
  # Prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_VERSION/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    curl -L -o qemu-aarch64-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_VERSION/qemu-aarch64-static.tar.gz &&
    tar xzf qemu-aarch64-static.tar.gz &&
    popd
script:
#  - 'make test'
  - 'make build-image'
  - 'make tag-image'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ;
      make push-image ;
      make manifest-list-image ;
    fi

# don't notify me when things fail
notifications:
  email: false
