sudo: required

services:
  - docker

before_install:
  - docker build -f latest/Dockerfile -t nodered/node-red-docker .
  - docker tag nodered/node-red-docker nodered/node-red-docker:$VERSION

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push nodered/node-red-docker

env:
  - VERSION=0.14.5
