# make use of vm's
sudo: 'required'

# have the docker service set up (we'll update it later)
services:
  - 'docker'

language:
  - 'bash'

env:
  global:
      - QEMU_VERSION=v2.11.1
      - NODE_RED_VERSION=0.18.4
      - IMAGE=raymondmm/node-red-test

before_install:
  - ./docker_hub.sh prepare

script:
  - ./docker_hub.sh build

after_success:
  - >
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;

      # Tag all images
      ./.docker/docker_hub.sh tag
      ./.docker/docker_hub.sh push
      ./.docker/docker_hub.sh manifest-list

      docker logout
    fi

# don't notify me when things fail
notifications:
  email: false
